window.AACStore = {
  cards: [
    // =========================
    // 🟡 PESSOAS
    // =========================

    {
      id: 1,
      category: "Pessoas",
      image: "icons/eu.png",
      frontText: "Eu",
      backText: "Eu",
    },
    {
      id: 2,
      category: "Pessoas",
      image: "icons/voce.png",
      frontText: "Você",
      backText: "Você",
    },
    {
      id: 3,
      category: "Pessoas",
      image: "https://cdn-icons-png.flaticon.com/512/4140/4140051.png",
      frontText: "Mamãe",
      backText: "Mamãe",
    },
    {
      id: 4,
      category: "Pessoas",
      image: "https://cdn-icons-png.flaticon.com/512/4140/4140048.png",
      frontText: "Papai",
      backText: "Papai",
    },
    {
      id: 5,
      category: "Pessoas",
      image: "icons/irmao.png",
      frontText: "Irmão",
      backText: "Irmão",
    },
    {
      id: 6,
      category: "Pessoas",
      image: "icons/irma.png",
      frontText: "Irmã",
      backText: "Irmã",
    },
    {
      id: 7,
      category: "Pessoas",
      image: "https://cdn-icons-png.flaticon.com/512/1000/1000370.png",
      frontText: "Amigo",
      backText: "Amigo",
    },
    {
      id: 8,
      category: "Pessoas",
      image: "https://cdn-icons-png.flaticon.com/512/1995/1995574.png",
      frontText: "Professor",
      backText: "Professor",
    },
    {
      id: 9,
      category: "Pessoas",
      image: "https://cdn-icons-png.flaticon.com/512/7697/7697560.png",
      frontText: "Vovó",
      backText: "Vovó",
    },
    {
      id: 10,
      category: "Pessoas",
      image: "https://cdn-icons-png.flaticon.com/512/6740/6740296.png",
      frontText: "Vovô",
      backText: "Vovô",
    },
    {
      id: 11,
      category: "Pessoas",
      image: "icons/ele.png",
      frontText: "Ele",
      backText: "Ele",
    },
    {
      id: 12,
      category: "Pessoas",
      image: "icons/ela.png",
      frontText: "Ela",
      backText: "Ela",
    },

    // =========================
    // 🟢 AÇÕES
    // =========================

    {
      id: 101,
      category: "Ações",
      image: "https://cdn-icons-png.flaticon.com/512/1046/1046784.png",
      frontText: "Comer",
      backText: "Comer",
    },
    {
      id: 102,
      category: "Ações",
      image: "icons/beber.png",
      frontText: "Beber",
      backText: "Beber",
    },
    {
      id: 103,
      category: "Ações",
      image: "https://cdn-icons-png.flaticon.com/512/686/686589.png",
      frontText: "Brincar",
      backText: "Brincar",
    },
    {
      id: 104,
      category: "Ações",
      image: "https://cdn-icons-png.flaticon.com/512/10303/10303407.png",
      frontText: "Dormir",
      backText: "Dormir",
    },
    {
      id: 105,
      category: "Ações",
      image: "icons/ir.png",
      frontText: "Ir",
      backText: "Ir",
    },
    {
      id: 106,
      category: "Ações",
      image: "icons/ver.png",
      frontText: "Ver",
      backText: "Ver",
    },
    {
      id: 107,
      category: "Ações",
      image: "https://cdn-icons-png.flaticon.com/512/3524/3524659.png",
      frontText: "Ajudar",
      backText: "Ajudar",
    },
    {
      id: 108,
      category: "Ações",
      image: "icons/parar.png",
      frontText: "Parar",
      backText: "Parar",
    },
    {
      id: 109,
      category: "Ações",
      image: "https://cdn-icons-png.flaticon.com/512/3043/3043888.png",
      frontText: "Correr",
      backText: "Correr",
    },
    {
      id: 110,
      category: "Ações",
      image: "https://cdn-icons-png.flaticon.com/512/6840/6840012.png",
      frontText: "Sentar",
      backText: "Sentar",
    },
    {
      id: 111,
      category: "Ações",
      image: "https://cdn-icons-png.flaticon.com/512/2593/2593782.png",
      frontText: "Levantar",
      backText: "Levantar",
    },
    {
      id: 112,
      category: "Ações",
      image: "icons/querer.png",
      frontText: "Querer",
      backText: "Querer",
    },
    {
      id: 113,
      category: "Ações",
      image: "icons/gostar.png",
      frontText: "Gostar",
      backText: "Gostar",
    },
    {
      id: 114,
      category: "Ações",
      image: "icons/fazer.png",
      frontText: "Fazer",
      backText: "Fazer",
    },
    {
      id: 115,
      category: "Ações",
      image: "icons/dar.png",
      frontText: "Dar",
      backText: "Dar",
    },
    {
      id: 116,
      category: "Ações",
      image: "icons/pegar.png",
      frontText: "Pegar",
      backText: "Pegar",
    },
    {
      id: 117,
      category: "Ações",
      image: "icons/precisar.png",
      frontText: "Precisar",
      backText: "Precisar",
    },
    {
      id: 118,
      category: "Ações",
      image: "icons/poder.png",
      frontText: "Poder",
      backText: "Poder",
    },
    {
      id: 119,
      category: "Ações",
      image: "icons/vir.png",
      frontText: "Vir",
      backText: "Vir",
    },
    {
      id: 120,
      category: "Ações",
      image: "icons/abrir.png",
      frontText: "Abrir",
      backText: "Abrir",
    },
    {
      id: 121,
      category: "Ações",
      image: "icons/fechar.png",
      frontText: "Fechar",
      backText: "Fechar",
    },
    {
      id: 122,
      category: "Ações",
      image: "icons/esperar.png",
      frontText: "Esperar",
      backText: "Esperar",
    },
    {
      id: 123,
      category: "Ações",
      image: "icons/colocar.png",
      frontText: "Colocar",
      backText: "Colocar",
    },
    {
      id: 124,
      category: "Ações",
      image: "icons/tirar.png",
      frontText: "Tirar",
      backText: "Tirar",
    },
    {
      id: 125,
      category: "Ações",
      image: "icons/andar.png",
      frontText: "Andar",
      backText: "Andar",
    },
    // =========================
    // 🟠 OBJETOS
    // =========================

    {
      id: 201,
      category: "Objetos",
      image: "https://cdn-icons-png.flaticon.com/512/824/824239.png",
      frontText: "Água",
      backText: "Água",
    },
    {
      id: 202,
      category: "Objetos",
      image: "icons/comida.png",
      frontText: "Comida",
      backText: "Comida",
    },
    {
      id: 203,
      category: "Objetos",
      image: "icons/bola.png",
      frontText: "Bola",
      backText: "Bola",
    },
    {
      id: 204,
      category: "Objetos",
      image: "icons/livro.png",
      frontText: "Livro",
      backText: "Livro",
    },
    {
      id: 205,
      category: "Objetos",
      image: "icons/tablet.png",
      frontText: "Tablet",
      backText: "Tablet",
    },
    {
      id: 206,
      category: "Objetos",
      image: "https://cdn-icons-png.flaticon.com/512/619/619034.png",
      frontText: "Banheiro",
      backText: "Banheiro",
    },
    {
      id: 207,
      category: "Objetos",
      image: "https://cdn-icons-png.flaticon.com/512/744/744465.png",
      frontText: "Carro",
      backText: "Carro",
    },
    {
      id: 208,
      category: "Objetos",
      image: "https://cdn-icons-png.flaticon.com/512/2586/2586738.png",
      frontText: "Celular",
      backText: "Celular",
    },
    {
      id: 209,
      category: "Objetos",
      image: "https://cdn-icons-png.flaticon.com/512/15177/15177944.png",
      frontText: "TV",
      backText: "TV",
    },
    {
      id: 210,
      category: "Objetos",
      image: "icons/casa.png",
      frontText: "Casa",
      backText: "Casa",
    },
    {
      id: 211,
      category: "Objetos",
      image: "icons/escola.png",
      frontText: "Escola",
      backText: "Escola",
    },
    {
      id: 212,
      category: "Objetos",
      image: "icons/roupa.png",
      frontText: "Roupa",
      backText: "Roupa",
    },
    {
      id: 213,
      category: "Objetos",
      image: "icons/maca.png",
      frontText: "Maçã",
      backText: "Maçã",
    },
    {
      id: 214,
      category: "Objetos",
      image: "icons/brinquedo.png",
      frontText: "Brinquedo",
      backText: "Brinquedo",
    },
    {
      id: 215,
      category: "Objetos",
      image: "icons/cama.png",
      frontText: "Cama",
      backText: "Cama",
    },
    {
      id: 216,
      category: "Objetos",
      image: "icons/mochila.png",
      frontText: "Mochila",
      backText: "Mochila",
    },
    {
      id: 217,
      category: "Objetos",
      image: "icons/onibus.png",
      frontText: "Ônibus",
      backText: "Ônibus",
    },
    // =========================
    // 🔵 DESCRIÇÕES
    // =========================

    {
      id: 301,
      category: "Descrições",
      image: "icons/grande.png",
      frontText: "Grande",
      backText: "Grande",
    },
    {
      id: 302,
      category: "Descrições",
      image: "icons/pequeno.png",
      frontText: "Pequeno",
      backText: "Pequeno",
    },
    {
      id: 303,
      category: "Descrições",
      image: "https://cdn-icons-png.flaticon.com/512/869/869869.png",
      frontText: "Quente",
      backText: "Quente",
    },
    {
      id: 304,
      category: "Descrições",
      image: "https://cdn-icons-png.flaticon.com/512/414/414927.png",
      frontText: "Frio",
      backText: "Frio",
    },
    {
      id: 305,
      category: "Descrições",
      image: "icons/bom.png",
      frontText: "Bom",
      backText: "Bom",
    },
    {
      id: 306,
      category: "Descrições",
      image: "icons/ruim.png",
      frontText: "Ruim",
      backText: "Ruim",
    },
    {
      id: 307,
      category: "Descrições",
      image: "icons/muito.png",
      frontText: "Muito",
      backText: "Muito",
    },
    {
      id: 308,
      category: "Descrições",
      image: "icons/pouco.png",
      frontText: "Pouco",
      backText: "Pouco",
    },
    {
      id: 309,
      category: "Descrições",
      image: "icons/mais.png",
      frontText: "Mais",
      backText: "Mais",
    },
    {
      id: 310,
      category: "Descrições",
      image: "icons/acabou.png",
      frontText: "Acabou",
      backText: "Acabou",
    },
    {
      id: 311,
      category: "Descrições",
      image: "icons/feliz.png",
      frontText: "Feliz",
      backText: "Feliz",
    },
    {
      id: 312,
      category: "Descrições",
      image: "icons/triste.png",
      frontText: "Triste",
      backText: "Triste",
    },
    {
      id: 313,
      category: "Descrições",
      image: "icons/cansado.png",
      frontText: "Cansado",
      backText: "Cansado",
    },
    {
      id: 314,
      category: "Descrições",
      image: "icons/rapido.png",
      frontText: "Rápido",
      backText: "Rápido",
    },
    {
      id: 315,
      category: "Descrições",
      image: "icons/devagar.png",
      frontText: "Devagar",
      backText: "Devagar",
    },
    {
      id: 316,
      category: "Descrições",
      image: "icons/molhado.png",
      frontText: "Molhado",
      backText: "Molhado",
    },

    // =========================
    // 🩷 SOCIAIS
    // =========================

    {
      id: 401,
      category: "Sociais",
      image: "icons/ola.png",
      frontText: "Olá",
      backText: "Olá",
    },
    {
      id: 402,
      category: "Sociais",
      image: "icons/tchau.png",
      frontText: "Tchau",
      backText: "Tchau",
    },
    {
      id: 403,
      category: "Sociais",
      image: "https://cdn-icons-png.flaticon.com/512/742/742748.png",
      frontText: "Obrigado",
      backText: "Obrigado",
    },
    {
      id: 404,
      category: "Sociais",
      image: "icons/desculpa.png",
      frontText: "Desculpa",
      backText: "Desculpa",
    },
    {
      id: 405,
      category: "Sociais",
      image: "https://cdn-icons-png.flaticon.com/512/742/742799.png",
      frontText: "Por favor",
      backText: "Por favor",
    },
    {
      id: 406,
      category: "Sociais",
      image: "icons/sim.png",
      frontText: "Sim",
      backText: "Sim",
    },
    {
      id: 407,
      category: "Sociais",
      image: "icons/nao.png",
      frontText: "Não",
      backText: "Não",
    },
    {
      id: 408,
      category: "Sociais",
      image: "icons/denada.png",
      frontText: "De nada",
      backText: "De nada",
    },
    {
      id: 409,
      category: "Sociais",
      image: "icons/comlicenca.png",
      frontText: "Com licença",
      backText: "Com licença",
    },
    {
      id: 410,
      category: "Sociais",
      image: "icons/parabens.png",
      frontText: "Parabéns",
      backText: "Parabéns",
    },
    // =========================
    // ⚪ GRAMÁTICA
    // =========================

    {
      id: 501,
      category: "Gramática",
      image: "icons/com.png",
      frontText: "com",
      backText: "com",
    },
    {
      id: 502,
      category: "Gramática",
      image: "icons/para.png",
      frontText: "para",
      backText: "para",
    },
    {
      id: 503,
      category: "Gramática",
      image: "icons/em.png",
      frontText: "em",
      backText: "em",
    },
    {
      id: 504,
      category: "Gramática",
      image: "icons/onde.png",
      frontText: "Onde?",
      backText: "Onde?",
    },
    {
      id: 505,
      category: "Gramática",
      image: "icons/quem.png",
      frontText: "Quem?",
      backText: "Quem?",
    },
    {
      id: 506,
      category: "Gramática",
      image: "icons/oque.png",
      frontText: "O quê?",
      backText: "O quê?",
    },
    {
      id: 507,
      category: "Gramática",
      image: "icons/quando.png",
      frontText: "Quando?",
      backText: "Quando?",
    },
    {
      id: 508,
      category: "Gramática",
      image: "icons/meu.png",
      frontText: "meu",
      backText: "meu",
    },
    {
      id: 509,
      category: "Gramática",
      image: "icons/minha.png",
      frontText: "minha",
      backText: "minha",
    },
    {
      id: 510,
      category: "Gramática",
      image: "icons/seu.png",
      frontText: "seu",
      backText: "seu",
    },
    {
      id: 511,
      category: "Gramática",
      image: "icons/sua.png",
      frontText: "sua",
      backText: "sua",
    },
    {
      id: 512,
      category: "Gramática",
      image: "icons/de.png",
      frontText: "de",
      backText: "de",
    },
    {
      id: 513,
      category: "Gramática",
      image: "icons/a.png",
      frontText: "a",
      backText: "a",
    },
    {
      id: 514,
      category: "Gramática",
      image: "icons/e.png",
      frontText: "e",
      backText: "e",
    },
    {
      id: 515,
      category: "Gramática",
      image: "icons/ou.png",
      frontText: "ou",
      backText: "ou",
    },
    {
      id: 516,
      category: "Gramática",
      image: "icons/aqui.png",
      frontText: "aqui",
      backText: "aqui",
    },
    {
      id: 517,
      category: "Gramática",
      image: "icons/agora.png",
      frontText: "agora",
      backText: "agora",
    },
  ],
  categories: [
    {
      name: "Pessoas",
      color: "#FACC15",
    },
    {
      name: "Ações",
      color: "#22C55E",
    },
    {
      name: "Objetos",
      color: "#F97316",
    },
    {
      name: "Descrições",
      color: "#3B82F6",
    },
    {
      name: "Sociais",
      color: "#EC4899",
    },
    {
      name: "Gramática",
      color: "#E5E7EB",
    },
  ],

  tags: [],
};
